<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7server.my.domain:
    roles:
      - default
      - rsyslog_server1
      - rsyslog_server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>

  el7client.my.domain:
    roles:
      - rsyslog_client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>

  el8server.wayout.org:
    roles:
      - rsyslog_server2
      - rsyslog_server
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 512

  el8client.wayout.org:
    roles:
      - rsyslog_client
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
  # vb_gui: true
