---
HOSTS:
  el9server.my.domain:
    roles:
    - default
    - rsyslog_server1
    - rsyslog_server
    - el9
    platform: el-9-x86_64
    box: almalinux/9
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    vagrant_memsize: 2048
    vagrant_cpus: 2
    family: almalinux-cloud/almalinux-9
    gce_machine_type: n1-standard-2
  el9client.my.domain:
    roles:
    - rsyslog_client
    - el9
    platform: el-9-x86_64
    box: almalinux/9
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    vagrant_memsize: 2048
    vagrant_cpus: 2
    family: almalinux-cloud/almalinux-9
    gce_machine_type: n1-standard-2
  el10server.wayout.org:
    roles:
    - rsyslog_server2
    - rsyslog_server
    - el10
    platform: el-10-x86_64
    box: almalinux/10
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    vagrant_memsize: 2048
    vagrant_cpus: 2
    # There are not currently any el10 images available on google cloud
    # family: almalinux-cloud/almalinux-10
    # gce_machine_type: n1-standard-2
  el10client.wayout.org:
    roles:
    - rsyslog_client
    - el10
    platform: el-10-x86_64
    box: almalinux/10
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    vagrant_memsize: 2048
    vagrant_cpus: 2
    # There are not currently any el10 images available on google cloud
    # family: almalinux-cloud/almalinux-10
    # gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'openvox8') %>"
